### ISSUE TITLE
Automatic update doesn't seem to take place

### ISSUE THREAD

**Issue by marcelgood** [Sunoo/homebridge-plugin-update-check#177]
I've turned on all the automatic update settings including using npm if Config UI isn't available, but it doesn't seem to be doing an automatic update. In the log I just see that there's an update, but then I have to manually do the update. Does this plugin not automatically update itself? When is the automatic update supposed to happen? At a specific hour of the day?

[9/14/2025, 6:00:56 AM] [Updates Available] Found 0 available update(s)
[9/14/2025, 1:05:00 PM] [Updates Available] Homebridge plugin update available: @homebridge-plugins/homebridge-plugin-update-check 2.3.3
[9/14/2025, 1:05:00 PM] [Updates Available] Found 1 available update(s)
[9/14/2025, 1:06:27 PM] [Updates Available] Initializing PluginUpdate platform...
[9/14/2025, 1:06:37 PM] [Updates Available] Found 0 available update(s)
[9/14/2025, 10:57:03 PM] [Updates Available] Initializing PluginUpdate platform...
[9/14/2025, 10:57:13 PM] [Updates Available] Found 0 available update(s)
[9/15/2025, 12:05:00 AM] [Updates Available] Found 0 available update(s)
[9/15/2025, 6:00:34 AM] [Updates Available] Initializing PluginUpdate platform...
[9/15/2025, 6:00:56 AM] [Updates Available] Found 0 available update(s)
[9/15/2025, 12:05:00 PM] [Updates Available] Homebridge plugin update available: @homebridge-plugins/homebridge-plugin-update-check 2.3.4
[9/15/2025, 12:05:00 PM] [Updates Available] Found 1 available update(s)

**Comment by donavanbecker** [comment]
@marcelgood Can you try: 1.0.7-beta.0

**Comment by marcelgood** [comment]
@donavanbecker 1.0.7-beta.0? I'm on v2.3.4 now? I do see this beta was just built, but why does it have such a low version number? Is this v2 code or v1 code?

**Comment by donavanbecker** [comment]
Sorry that was an accident, should be 2.3.5 beta now

**Comment by donavanbecker** [comment]
Published on NPM - 2.3.5-beta.2

**Comment by marcelgood** [comment]
Thank you. Installed now. I'll see how it goes.

**Comment by marcelgood** [comment]
This is not working at all now. My Homebridge got into an endless loop trying to update to beta.3. Looks like this feature is not ready for prime time. I went back to the latest release version to get back to a stable installation.

**Comment by donavanbecker** [comment]
@marcelgood Any info you can provide? Not really able to fix anything if you don't provide me with any logs.

**Comment by marcelgood** [comment]
@donavanbecker Sorry, I had to bail out, because it was creating havoc. One of my plugins locked me out, because the continued restart hammered its API, so now I have deal with that. But here's what I could capture. It detects that there's a newer version, then claims it updated it successfully and restarts Homebridge, but then it loads the old version again and the spiel continued until I was able to manually install the release version and stop the loop. 

```
[9/15/2025, 9:40:24 PM] [Updates Available] Homebridge plugin update available: @homebridge-plugins/homebridge-plugin-update-check 2.3.5-beta.3
[9/15/2025, 9:40:24 PM] [Updates Available] Found 1 available update(s)
[9/15/2025, 9:40:24 PM] [Updates Available] Automatic updates enabled - preparing to install updates
[9/15/2025, 9:40:24 PM] [Updates Available] Creating backup before performing updates
[9/15/2025, 9:40:24 PM] [Updates Available] Creating backup before performing updates
[9/15/2025, 9:40:24 PM] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-1NJ16m/homebridge-backup-0EE3B2EEE244.1757997624133.tar.gz.
[9/15/2025, 9:40:24 PM] [Updates Available] Backup created successfully via UI API (/api/backup)
[9/15/2025, 9:40:24 PM] [Updates Available] Attempting automatic update: @homebridge-plugins/homebridge-plugin-update-check 2.3.5-beta.2 → 2.3.5-beta.3
[9/15/2025, 9:40:24 PM] [Updates Available] Attempting to update plugin @homebridge-plugins/homebridge-plugin-update-check to 2.3.5-beta.3
[9/15/2025, 9:40:26 PM] [Updates Available] Plugin @homebridge-plugins/homebridge-plugin-update-check update command completed successfully (
changed 44 packages in 2s
)
[9/15/2025, 9:40:26 PM] [Updates Available] Successfully updated Plugin: @homebridge-plugins/homebridge-plugin-update-check to 2.3.5-beta.3
[9/15/2025, 9:40:26 PM] [Updates Available] Updates completed successfully - restarting Homebridge to apply changes
[9/15/2025, 9:40:26 PM] [Updates Available] Attempting to restart Homebridge to apply updates
[9/15/2025, 9:40:26 PM] [Homebridge UI] Homebridge restart request received.
[9/15/2025, 9:40:26 PM] [Homebridge UI] UI/Bridge settings have not changed - only restarting Homebridge process.
[9/15/2025, 9:40:26 PM] [Homebridge UI] Sending SIGTERM to Homebridge...
[9/15/2025, 9:40:26 PM] Got SIGTERM, shutting down Homebridge...
[9/15/2025, 9:40:26 PM] [Updates Available] Homebridge restart initiated via UI API (/api/server/restart)
[9/15/2025, 9:40:31 PM] [HB Supervisor] Homebridge process ended. Code: 143, signal: null.
[9/15/2025, 9:40:36 PM] [HB Supervisor] Restarting Homebridge...
[9/15/2025, 9:40:36 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution.
[9/15/2025, 9:40:36 PM] [HB Supervisor] Started Homebridge v1.11.0 with PID: 24816.
[9/15/2025, 9:40:37 PM] Loaded config.json with 0 accessories and 5 platforms.
[9/15/2025, 9:40:37 PM] Loaded 12 cached accessories from cachedAccessories.
[9/15/2025, 9:40:38 PM] ---
[9/15/2025, 9:40:38 PM] Loaded plugin: homebridge-homeconnect@1.6.2
[9/15/2025, 9:40:38 PM] Registering platform 'homebridge-homeconnect.HomeConnect'
[9/15/2025, 9:40:38 PM] ---
[9/15/2025, 9:40:38 PM] Loaded plugin: homebridge-nest@4.6.10
[9/15/2025, 9:40:38 PM] Registering platform 'homebridge-nest.Nest'
[9/15/2025, 9:40:38 PM] ---
[9/15/2025, 9:40:41 PM] Loaded plugin: homebridge-ring@14.0.1
[9/15/2025, 9:40:41 PM] Registering platform 'homebridge-ring.Ring'
[9/15/2025, 9:40:41 PM] ---
[9/15/2025, 9:40:42 PM] Loaded plugin: @homebridge-plugins/homebridge-plugin-update-check@2.3.5-beta.2
[9/15/2025, 9:40:42 PM] Registering platform '@homebridge-plugins/homebridge-plugin-update-check.PluginUpdate'
```

**Comment by marcelgood** [comment]
I think it's installing the updated plugin in the wrong location. It's installing it in /opt/homebridge/lib/node_modules, instead of /var/lib/homebridge/node_modules. 

<img width="816" height="216" alt="Image" src="https://github.com/user-attachments/assets/91f62ee8-5bd8-448c-aa3e-5b0bfc1c29a7" />

<img width="631" height="190" alt="Image" src="https://github.com/user-attachments/assets/08aa068b-7fdf-417f-9f15-bb2e3a9887ec" />

**Comment by SemoTech** [comment]
@donavanbecker has this been fixed?  It seems several of my plugins are NOT being updated by this plugin anymore.

Running v2.3.7 of this plugin in Docker and noticed two of my other plugins (Denon TV and Homebridge Govee) were not being updated for a while, even tho they were not set to ignore updates.

Here is how your plugin is configured:

<img width="880" height="3220" alt="Image" src="https://github.com/user-attachments/assets/3c953d27-9959-4c6b-bf3d-d8f0b9aa131a" />

Here are the other 2 plugins:

<img width="791" height="525" alt="Image" src="https://github.com/user-attachments/assets/aae1e947-d5ba-4e20-8602-2ce9011224c2" />

<img width="789" height="538" alt="Image" src="https://github.com/user-attachments/assets/0d4592bc-30a8-4cf2-b5b1-c13c4409b338" />

Would appreciate a fix and will wait a bit to manually update those 2 plugins in the hope that your new version fixes this...  Thanks!

**Comment by EjvindHald** [comment]
I am also running version 2.3.7 in Docker, and I do not see any updates taken place. I have enabled all update types. 

The JSON looks like this:

>         {
            "name": "PluginUpdate",
            "sensorType": "contact",
            "checkHomebridgeUpdates": true,
            "checkHomebridgeUIUpdates": true,
            "checkPluginUpdates": true,
            "checkDockerUpdates": true,
            "autoUpdateHomebridge": true,
            "autoUpdateHomebridgeUI": true,
            "autoUpdatePlugins": true,
            "allowDirectNpmUpdates": true,
            "autoRestartAfterUpdates": true,
            "failureSensorType": "motion",
            "platform": "PluginUpdate"
        }

and it is shown accordingly in the Homebridge UI.

The log shows:

> [1/4/2026, 4:16:38 PM] [PluginUpdate] Homebridge UI update available: 5.14.0
[1/4/2026, 4:16:38 PM] [PluginUpdate] Docker update available: 2026-01-03
[1/4/2026, 4:16:38 PM] [PluginUpdate] Found 2 available update(s)

I would have expected it do update the Homebridge UI, but nothing happens. 

I can see that sufficient permissions are needed, and I am not quite sure how to check and configure this.

Finally, a sensor type contact is exposed in Homekit as described. What does it indicate and what is the purpose?

Hope someone can point me in the right direction. Thanks.

**Comment by donavanbecker** [comment]
Please try `2.3.8-beta.1`

**Comment by EjvindHald** [comment]
> Please try `2.3.8-beta.1`

It is working fine now - thanks!

What does the contact sensor exposed in Homekit indicate?

**Comment by SemoTech** [comment]
Sorry but still not working for me @donavanbecker.  Here is the log after upgrading to v2.3.8-beta.2

```
[1/5/2026, 1:04:44 PM] Got SIGTERM, shutting down child bridge process...
[1/5/2026, 1:04:49 PM] [PluginUpdate] Child bridge process ended
[1/5/2026, 1:04:49 PM] [PluginUpdate] Process Ended. Code: 143, Signal: null
[1/5/2026, 1:04:56 PM] [PluginUpdate] Restarting Process...
[1/5/2026, 1:04:57 PM] [PluginUpdate] Launched child bridge with PID 1338
[1/5/2026, 1:04:57 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.2 child bridge successfully
[1/5/2026, 1:05:00 PM] [PluginUpdate] Homebridge plugin update available: @homebridge-plugins/homebridge-govee 11.14.0
[1/5/2026, 1:05:00 PM] [PluginUpdate] Homebridge plugin update available: homebridge-denon-tv 6.1.0
[1/5/2026, 1:05:00 PM] [PluginUpdate] Found 2 available update(s)
[1/5/2026, 1:05:00 PM] [PluginUpdate] Creating backup before performing updates
[1/5/2026, 1:05:00 PM] [PluginUpdate] ERR_BAD_REQUEST error connecting to http://localhost:8581/api/backup/create
[1/5/2026, 1:05:00 PM] [PluginUpdate] Backup created successfully via UI API (/api/backup/create)
[1/5/2026, 1:05:00 PM] [PluginUpdate] Attempting to update plugin @homebridge-plugins/homebridge-govee to 11.14.0
[1/5/2026, 1:05:00 PM] [PluginUpdate] Package not installed
[1/5/2026, 1:05:00 PM] [PluginUpdate] Failed to queue update for plugin @homebridge-plugins/homebridge-govee
[1/5/2026, 1:05:00 PM] [PluginUpdate] Attempting to update plugin homebridge-denon-tv to 6.1.0
[1/5/2026, 1:05:00 PM] [PluginUpdate] Plugin homebridge-denon-tv update queued successfully (version: 6.1.0)
[1/5/2026, 1:05:00 PM] [PluginUpdate] Attempting to restart Homebridge to apply updates
[1/5/2026, 1:05:00 PM] [PluginUpdate] Automatic update failed for @homebridge-plugins/homebridge-govee@11.14.0
[1/5/2026, 1:05:00 PM] [PluginUpdate] Homebridge restart initiated via UI API (/api/server/restart)
[1/5/2026, 1:05:11 PM] [PluginUpdate] Initializing PluginUpdate platform...
[1/5/2026, 1:05:11 PM] [PluginUpdate] Initializing child bridge 0E:0C:B8:EC:49:34
[1/5/2026, 1:05:11 PM] [PluginUpdate] Launched child bridge with PID 1426
[1/5/2026, 1:05:11 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.2 child bridge successfully
[1/5/2026, 1:05:21 PM] [PluginUpdate] Homebridge plugin update available: @homebridge-plugins/homebridge-govee 11.14.0
[1/5/2026, 1:05:21 PM] [PluginUpdate] Found 1 available update(s)
[1/5/2026, 1:05:21 PM] [PluginUpdate] Creating backup before performing updates
[1/5/2026, 1:05:21 PM] [PluginUpdate] ERR_BAD_REQUEST error connecting to http://localhost:8581/api/backup/create
[1/5/2026, 1:05:21 PM] [PluginUpdate] Backup created successfully via UI API (/api/backup/create)
[1/5/2026, 1:05:21 PM] [PluginUpdate] Attempting to update plugin @homebridge-plugins/homebridge-govee to 11.14.0
[1/5/2026, 1:05:21 PM] [PluginUpdate] Package not installed
[1/5/2026, 1:05:21 PM] [PluginUpdate] Failed to queue update for plugin @homebridge-plugins/homebridge-govee
[1/5/2026, 1:05:21 PM] [PluginUpdate] Automatic update failed for @homebridge-plugins/homebridge-govee@11.14.0
```

**Comment by donavanbecker** [comment]
@SemoTech, please try `2.3.8-beta.3`

**Comment by SemoTech** [comment]
> [@SemoTech](https://github.com/SemoTech), please try `2.3.8-beta.3`

Thanks @donavanbecker looks like we are getting close...  There is still a backups error...

```
[1/5/2026, 1:27:50 PM] Got SIGTERM, shutting down child bridge process...
[1/5/2026, 1:27:50 PM] [PluginUpdate] Restarting child bridge...
[1/5/2026, 1:27:55 PM] [PluginUpdate] Child bridge process ended
[1/5/2026, 1:27:55 PM] [PluginUpdate] Process Ended. Code: 143, Signal: null
[1/5/2026, 1:28:02 PM] [PluginUpdate] Restarting Process...
[1/5/2026, 1:28:02 PM] [PluginUpdate] Launched child bridge with PID 3595
[1/5/2026, 1:28:02 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.3 child bridge successfully
[1/5/2026, 1:28:12 PM] [PluginUpdate] Homebridge plugin update available: @homebridge-plugins/homebridge-govee 11.14.0
[1/5/2026, 1:28:12 PM] [PluginUpdate] Found 1 available update(s)


[1/5/2026, 1:28:12 PM] [PluginUpdate] Creating backup before performing updates
[1/5/2026, 1:28:12 PM] [PluginUpdate] ERR_BAD_REQUEST error connecting to http://localhost:8581/api/backup/create


[1/5/2026, 1:28:12 PM] [PluginUpdate] Backup created successfully via UI API (/api/backup/create)
[1/5/2026, 1:28:12 PM] [PluginUpdate] Attempting to update plugin @homebridge-plugins/homebridge-govee to 11.14.0
[1/5/2026, 1:28:12 PM] [PluginUpdate] Plugin @homebridge-plugins/homebridge-govee update queued successfully (version: 11.14.0)
[1/5/2026, 1:28:12 PM] [PluginUpdate] Attempting to restart Homebridge to apply updates
[1/5/2026, 1:28:12 PM] [PluginUpdate] Homebridge restart initiated via UI API (/api/server/restart)
[1/5/2026, 1:28:24 PM] [PluginUpdate] Initializing PluginUpdate platform...
[1/5/2026, 1:28:24 PM] [PluginUpdate] Initializing child bridge 0E:0C:B8:EC:49:34
[1/5/2026, 1:28:24 PM] [PluginUpdate] Launched child bridge with PID 3827
[1/5/2026, 1:28:24 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.3 child bridge successfully
[1/5/2026, 1:28:35 PM] [PluginUpdate] Initializing PluginUpdate platform...
[1/5/2026, 1:28:35 PM] [PluginUpdate] Initializing child bridge 0E:0C:B8:EC:49:34
[1/5/2026, 1:28:35 PM] [PluginUpdate] Launched child bridge with PID 3909
[1/5/2026, 1:28:35 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.3 child bridge successfully
```

**Comment by SemoTech** [comment]
Hi @donavanbecker I also just upgraded to latest beta 4 and even more backup errors:

```[1/5/2026, 1:57:23 PM] [PluginUpdate] Restarting child bridge...
[1/5/2026, 1:57:23 PM] Got SIGTERM, shutting down child bridge process...
[1/5/2026, 1:57:28 PM] [PluginUpdate] Child bridge process ended
[1/5/2026, 1:57:28 PM] [PluginUpdate] Process Ended. Code: 143, Signal: null
[1/5/2026, 1:57:35 PM] [PluginUpdate] Restarting Process...
[1/5/2026, 1:57:35 PM] [PluginUpdate] Launched child bridge with PID 8130
[1/5/2026, 1:57:35 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.4 child bridge successfully
[1/5/2026, 1:57:45 PM] [PluginUpdate] Homebridge plugin update available: homebridge-denon-tv 6.1.0
[1/5/2026, 1:57:45 PM] [PluginUpdate] Found 1 available update(s)
[1/5/2026, 1:57:45 PM] [PluginUpdate] Creating backup before performing updates

**_[1/5/2026, 1:57:45 PM] [PluginUpdate] ERR_BAD_REQUEST error connecting to http://127.0.0.1:8581/api/backup/create (status 404)
[1/5/2026, 1:57:45 PM] [PluginUpdate] ERR_BAD_REQUEST error connecting to http://127.0.0.1:8581/api/backups/create (status 404)
[1/5/2026, 1:57:46 PM] [PluginUpdate] ERR_BAD_REQUEST error connecting to http://127.0.0.1:8581/api/server/backup (status 404)
[1/5/2026, 1:57:46 PM] [PluginUpdate] All backup endpoints failed - backup creation unavailable
[1/5/2026, 1:57:46 PM] [PluginUpdate] Unable to create Homebridge backup before automatic updates - proceeding without backup_**

[1/5/2026, 1:57:46 PM] [PluginUpdate] Attempting to update plugin homebridge-denon-tv to 6.1.0
[1/5/2026, 1:57:46 PM] [PluginUpdate] Plugin homebridge-denon-tv update queued successfully (version: 6.1.0)
[1/5/2026, 1:57:46 PM] [PluginUpdate] Attempting to restart Homebridge to apply updates
[1/5/2026, 1:57:46 PM] [PluginUpdate] Homebridge restart initiated via UI API (/api/server/restart)
[1/5/2026, 1:57:57 PM] [PluginUpdate] Initializing PluginUpdate platform...
[1/5/2026, 1:57:57 PM] [PluginUpdate] Initializing child bridge 0E:0C:B8:EC:49:34
[1/5/2026, 1:57:58 PM] [PluginUpdate] Launched child bridge with PID 8217
[1/5/2026, 1:57:58 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.4 child bridge successfully```

**Comment by SemoTech** [comment]
@donavanbecker as you work for fix these last backup issues, maybe you can add to the log data the current plugin version as well.

i.e, instead of just: "Attempting to update plugin _homebridge-denon-tv_ to 6.1.0"
display:  "Attempting to update plugin _homebridge-denon-tv_ from v6.0.1 to v6.1.0"

This way there is a log of the previous version, in case one needs to manually downgrade...

Thanks in advance for all your efforts!

**Comment by donavanbecker** [comment]
> i.e, instead of just: "Attempting to update plugin _homebridge-denon-tv_ to 6.1.0" display: "Attempting to update plugin _homebridge-denon-tv_ from v6.0.1 to v6.1.0"

Done!

**Comment by SemoTech** [comment]
> > i.e, instead of just: "Attempting to update plugin _homebridge-denon-tv_ to 6.1.0" display: "Attempting to update plugin _homebridge-denon-tv_ from v6.0.1 to v6.1.0"
> 
> Done!

Outstanding @donavanbecker and much appreciated!

Looks like your plugin v2.3.8-beta.7 is the last one for homebridge v1.11.1 (latest docker 2026-01-03 image available) so I upgraded to that.  

Your plugin v2.3.8-beta.7 works to update others, but the backups still don't seem to work (I do see you suppressed the ugly errors).  

Any idea why backups are failing to be created under Docker and is that fixed in v3.0.x of the plugin?  If so I can test when the docker image for Homebridge 2.x comes out...


[1/5/2026, 2:47:46 PM] [PluginUpdate] Child bridge process ended
[1/5/2026, 2:47:46 PM] [PluginUpdate] Process Ended. Code: 143, Signal: null
[1/5/2026, 2:47:53 PM] [PluginUpdate] Restarting Process...
[1/5/2026, 2:47:53 PM] [PluginUpdate] Launched child bridge with PID 12944
[1/5/2026, 2:47:53 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.7 child bridge successfully
[1/5/2026, 2:48:03 PM] [PluginUpdate] Homebridge plugin update available: @0x5e/homebridge-tuya-platform 1.7.0-beta.54
[1/5/2026, 2:48:03 PM] [PluginUpdate] Found 1 available update(s)
[1/5/2026, 2:48:03 PM] [PluginUpdate] Creating backup before performing updates

**_[1/5/2026, 2:48:04 PM] [PluginUpdate] Backup not available - proceeding with updates without backup_**

[1/5/2026, 2:48:04 PM] [PluginUpdate] Attempting to update plugin @0x5e/homebridge-tuya-platform from v1.7.0-beta.50 to v1.7.0-beta.54
[1/5/2026, 2:48:04 PM] [PluginUpdate] Plugin @0x5e/homebridge-tuya-platform update queued successfully (version: 1.7.0-beta.54)
[1/5/2026, 2:48:04 PM] [PluginUpdate] Attempting to restart Homebridge to apply updates
[1/5/2026, 2:48:04 PM] [PluginUpdate] Homebridge restart initiated via UI API (/api/server/restart)
[1/5/2026, 2:48:15 PM] [PluginUpdate] Initializing PluginUpdate platform...
[1/5/2026, 2:48:15 PM] [PluginUpdate] Initializing child bridge 0E:0C:B8:EC:49:34
[1/5/2026, 2:48:16 PM] [PluginUpdate] Launched child bridge with PID 13056
[1/5/2026, 2:48:16 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.7 child bridge successfully
[1/5/2026, 2:48:25 PM] [PluginUpdate] Initializing PluginUpdate platform...
[1/5/2026, 2:48:25 PM] [PluginUpdate] Initializing child bridge 0E:0C:B8:EC:49:34
[1/5/2026, 2:48:25 PM] [PluginUpdate] Launched child bridge with PID 13124
[1/5/2026, 2:48:25 PM] [PluginUpdate] Loaded @homebridge-plugins/homebridge-plugin-update-check v2.3.8-beta.7 child bridge successfully
